/** @type {import('tailwindcss').Config} */
import daisyui from 'daisyui';

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'acnh-green': '#88C9A1',
        'acnh-green-dark': '#75B08A',
        'acnh-green-light': '#A8D9BB',
        'acnh-mint': '#B8E6D2',
        'acnh-leaf': '#4FC1A6',
        'acnh-sky': '#8ECBDE',
        'acnh-yellow': '#F8B856',
        'acnh-pink': '#F5A7B2',
        'acnh-beige': '#F5E6D3',
        'acnh-cream': '#FFF9E8',
        'acnh-brown': '#B69B7D',
        'acnh-brown-light': '#D4C5B3',
      },
      backgroundColor: {
        primary: '#88C9A1',
        'primary-dark': '#75B08A',
        'primary-light': '#A8D9BB',
        secondary: '#F5E6D3',
      },
      textColor: {
        primary: '#75B08A',
        secondary: '#B69B7D',
      },
      borderColor: {
        primary: '#88C9A1',
        secondary: '#F5E6D3',
      },
      fontFamily: {
        sans: ['"Zen Maru Gothic"', 'sans-serif'],
        serif: ['"Kiwi Maru"', 'serif'],
        kiwi: ['"Kiwi Maru"', 'serif'],
        zen: ['"Zen Maru Gothic"', 'sans-serif'],
      },
      borderRadius: {
        acnh: '2rem',
      },
      boxShadow: {
        acnh: '0 4px 0 rgba(117, 176, 138, 0.2)',
        'acnh-green': '0 4px 0 rgba(117, 176, 138, 0.3)',
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        light: {
          primary: '#88C9A1',
          secondary: '#F5E6D3',
          accent: '#4FC1A6',
          neutral: '#B69B7D',
          'base-100': '#FFF9E8',
          'base-200': '#F5E6D3',
          'base-300': '#D4C5B3',
          info: '#8ECBDE',
          success: '#A8D9BB',
          warning: '#F8B856',
          error: '#F5A7B2',
          '--rounded-box': '2rem',
          '--rounded-btn': '1.5rem',
          '--rounded-badge': '1.2rem',
          '--animation-btn': '0.25s',
          '--animation-input': '0.2s',
          '--btn-focus-scale': '0.95',
          '--border-btn': '2px',
          '--tab-border': '2px',
          '--tab-radius': '1rem',
        },
        dark: {
          primary: '#75B08A',
          secondary: '#D4C5B3',
          accent: '#4FC1A6',
          neutral: '#B69B7D',
          'base-100': '#2A3830',
          'base-200': '#374B3E',
          'base-300': '#445C4C',
          info: '#8ECBDE',
          success: '#88C9A1',
          warning: '#F8B856',
          error: '#F5A7B2',
          '--rounded-box': '2rem',
          '--rounded-btn': '1.5rem',
          '--rounded-badge': '1.2rem',
          '--animation-btn': '0.25s',
          '--animation-input': '0.2s',
          '--btn-focus-scale': '0.95',
          '--border-btn': '2px',
          '--tab-border': '2px',
          '--tab-radius': '1rem',
        },
      },
    ],
    base: true,
    styled: true,
    utils: true,
    prefix: '',
    logs: true,
    themeRoot: '.',
  },
};
